name: IPFX Nightly onprem tests
on:
  schedule:
    - cron: '05 6 * * *'


jobs:
  onprem:
    name: on-prem tests
    runs-on: ["self-hosted"]
    strategy:
      matrix:
        image: ["ipfx_py39:latest", "ipfx_py311:latest"]
        branch: ["master", "feature/**"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - name: run test in docker
        run: |
          docker run \
          --mount type=bind,source=$PWD,target=/local1/github_worker,bind-propagation=rshared \
          -v /data/informatics/module_test_data/:/data/informatics/module_test_data/ \
          -v /allen/aibs/informatics/module_test_data/:/allen/aibs/informatics/module_test_data/ \
          -v /allen/programs/celltypes/production/mousecelltypes/:/allen/programs/celltypes/production/mousecelltypes/ \
          -v /allen/programs/celltypes/workgroups/279/:/allen/programs/celltypes/workgroups/279/ \
          -v /allen/programs/celltypes/production/humancelltypes/:/allen/programs/celltypes/production/humancelltypes/ \
          --workdir /local1/github_worker --rm \
          --user 1001:1001 \
          ${{ matrix.image }} \
              /bin/bash -c "python -m venv .venv; \
                            source .venv/bin/activate; \
                            pip install --upgrade pip; \
                            pip install numpy; \
                            pip install -r requirements.txt; \
                            export TEST_API_ENDPOINT=http://api.brain-map.org; \
                            pip install -r requirements-test.txt; \
                            git config lfs.url 'https://github.com/AllenInstitute/ipfx.git/info/lfs'; \
                            git lfs env; \
                            git lfs pull; \
                            python -m pytest \
                              --junitxml=test-reports/test.xml --verbose"
