name: IPFX Nightly onprem tests
on:
  schedule:
    - cron: '05 6 * * *'


jobs:
  onprem:
    name: on-prem tests
    runs-on: ["self-hosted"]
    strategy:
      matrix:
        pyver: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14-rc"]
        branch: ["master", "feature/**"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - name: Build docker image
        run: |
          docker build --build-arg PYTHON_VERSION="${{ matrix.pyver }}" -t "ipfx_${{ matrix.pyver }}:latest" docker
      - name: Run test in docker
        run: |
          DOCKER_IMAGE="ipfx_${{ matrix.pyver }}:latest" ./docker/run_tests_with_docker.sh
